/**
 * 국가 이름(영문)을 ISO 3166-1 alpha-2 코드로 매핑
 * world-atlas의 countries-110m.json에서 사용하는 국가 이름 기반
 */

export const COUNTRY_NAME_TO_CODE = {
  // 아시아
  'South Korea': 'KR',
  'Korea': 'KR',
  'China': 'CN',
  'Japan': 'JP',
  'India': 'IN',
  'Indonesia': 'ID',
  'Thailand': 'TH',
  'Vietnam': 'VN',
  'Philippines': 'PH',
  'Malaysia': 'MY',
  'Singapore': 'SG',
  'Myanmar': 'MM',
  'Cambodia': 'KH',
  'Laos': 'LA',
  'Brunei': 'BN',
  'East Timor': 'TL',
  'Timor-Leste': 'TL',
  'Afghanistan': 'AF',
  'Bangladesh': 'BD',
  'Bhutan': 'BT',
  'Maldives': 'MV',
  'Nepal': 'NP',
  'Pakistan': 'PK',
  'Sri Lanka': 'LK',
  'Kazakhstan': 'KZ',
  'Kyrgyzstan': 'KG',
  'Tajikistan': 'TJ',
  'Turkmenistan': 'TM',
  'Uzbekistan': 'UZ',
  'Mongolia': 'MN',
  'North Korea': 'KP',
  'Taiwan': 'TW',
  'Hong Kong': 'HK',
  'Macao': 'MO',
  'United Arab Emirates': 'AE',
  'Bahrain': 'BH',
  'Iraq': 'IQ',
  'Iran': 'IR',
  'Israel': 'IL',
  'Jordan': 'JO',
  'Kuwait': 'KW',
  'Lebanon': 'LB',
  'Oman': 'OM',
  'Palestine': 'PS',
  'Qatar': 'QA',
  'Saudi Arabia': 'SA',
  'Syria': 'SY',
  'Turkey': 'TR',
  'Yemen': 'YE',
  
  // 유럽
  'United Kingdom': 'GB',
  'France': 'FR',
  'Germany': 'DE',
  'Italy': 'IT',
  'Spain': 'ES',
  'Netherlands': 'NL',
  'Belgium': 'BE',
  'Switzerland': 'CH',
  'Austria': 'AT',
  'Sweden': 'SE',
  'Norway': 'NO',
  'Denmark': 'DK',
  'Finland': 'FI',
  'Poland': 'PL',
  'Portugal': 'PT',
  'Greece': 'GR',
  'Ireland': 'IE',
  'Czech Republic': 'CZ',
  'Czechia': 'CZ',
  'Hungary': 'HU',
  'Romania': 'RO',
  'Bulgaria': 'BG',
  'Croatia': 'HR',
  'Slovakia': 'SK',
  'Slovenia': 'SI',
  'Estonia': 'EE',
  'Latvia': 'LV',
  'Lithuania': 'LT',
  'Luxembourg': 'LU',
  'Malta': 'MT',
  'Cyprus': 'CY',
  'Iceland': 'IS',
  'Russia': 'RU',
  'Ukraine': 'UA',
  'Belarus': 'BY',
  'Moldova': 'MD',
  'Albania': 'AL',
  'Bosnia and Herzegovina': 'BA',
  'Montenegro': 'ME',
  'North Macedonia': 'MK',
  'Macedonia': 'MK',
  'Serbia': 'RS',
  'Kosovo': 'XK',
  
  // 아메리카
  'United States of America': 'US',
  'United States': 'US',
  'Canada': 'CA',
  'Mexico': 'MX',
  'Brazil': 'BR',
  'Argentina': 'AR',
  'Chile': 'CL',
  'Colombia': 'CO',
  'Peru': 'PE',
  'Venezuela': 'VE',
  'Ecuador': 'EC',
  'Bolivia': 'BO',
  'Paraguay': 'PY',
  'Uruguay': 'UY',
  'Guyana': 'GY',
  'Suriname': 'SR',
  'French Guiana': 'GF',
  'Falkland Islands': 'FK',
  'Cuba': 'CU',
  'Jamaica': 'JM',
  'Haiti': 'HT',
  'Dominican Republic': 'DO',
  'Puerto Rico': 'PR',
  'Trinidad and Tobago': 'TT',
  'Costa Rica': 'CR',
  'Panama': 'PA',
  'Nicaragua': 'NI',
  'Honduras': 'HN',
  'El Salvador': 'SV',
  'Guatemala': 'GT',
  'Belize': 'BZ',
  
  // 오세아니아
  'Australia': 'AU',
  'New Zealand': 'NZ',
  'Papua New Guinea': 'PG',
  'Fiji': 'FJ',
  'Solomon Islands': 'SB',
  'Vanuatu': 'VU',
  'New Caledonia': 'NC',
  'French Polynesia': 'PF',
  
  // 아프리카
  'South Africa': 'ZA',
  'Egypt': 'EG',
  'Kenya': 'KE',
  'Ethiopia': 'ET',
  'Nigeria': 'NG',
  'Ghana': 'GH',
  'Tanzania': 'TZ',
  'Uganda': 'UG',
  'Rwanda': 'RW',
  'Zimbabwe': 'ZW',
  'Zambia': 'ZM',
  'Malawi': 'MW',
  'Mozambique': 'MZ',
  'Morocco': 'MA',
  'Tunisia': 'TN',
  'Algeria': 'DZ',
  'Libya': 'LY',
  'Sudan': 'SD',
  'South Sudan': 'SS',
  'Somalia': 'SO',
  'Djibouti': 'DJ',
  'Eritrea': 'ER',
  'Madagascar': 'MG',
  'Mauritius': 'MU',
  'Seychelles': 'SC',
  'Cameroon': 'CM',
  'Gabon': 'GA',
  'Republic of the Congo': 'CG',
  'Congo': 'CG',
  'Democratic Republic of the Congo': 'CD',
  'Angola': 'AO',
  'Namibia': 'NA',
  'Botswana': 'BW',
  'Lesotho': 'LS',
  'Eswatini': 'SZ',
  'Burundi': 'BI',
  'Chad': 'TD',
  'Niger': 'NE',
  'Mali': 'ML',
  'Burkina Faso': 'BF',
  'Senegal': 'SN',
  'Gambia': 'GM',
  'Guinea-Bissau': 'GW',
  'Guinea': 'GN',
  'Sierra Leone': 'SL',
  'Liberia': 'LR',
  'Ivory Coast': 'CI',
  'Côte d\'Ivoire': 'CI',
  'Togo': 'TG',
  'Benin': 'BJ',
  'Mauritania': 'MR',
  
  // 기타
  'Greenland': 'GL',
  'Western Sahara': 'EH',
  'W. Sahara': 'EH',
}

/**
 * 국가 이름으로 ISO 코드 조회
 * @param {string} countryName - 국가 이름
 * @returns {string|null} ISO 3166-1 alpha-2 코드 또는 null
 */
export function getCountryCodeFromName(countryName) {
  if (!countryName) return null
  
  // 정확한 매칭 시도
  if (COUNTRY_NAME_TO_CODE[countryName]) {
    return COUNTRY_NAME_TO_CODE[countryName]
  }
  
  // 대소문자 무시 매칭
  const normalizedName = countryName.trim()
  for (const [name, code] of Object.entries(COUNTRY_NAME_TO_CODE)) {
    if (name.toLowerCase() === normalizedName.toLowerCase()) {
      return code
    }
  }
  
  return null
}

