/**
 * 네모 로직 퍼즐 데이터
 * solution: true = 칠해야 하는 칸, false = 빈 칸
 * 난이도별로 정렬: 초급(5x5) → 중급(10x10) → 고급(15x15)
 */

export const NONOGRAM_PUZZLES = [
  // ========== 초급 (5×5) ==========
  {
    id: 'heart-5x5',
    name: '하트',
    size: 5,
    description: '초급 - 작은 하트',
    solution: [
      [false, true, false, true, false],
      [true, true, true, true, true],
      [true, true, true, true, true],
      [false, true, true, true, false],
      [false, false, true, false, false],
    ],
  },
  {
    id: 'smile-5x5',
    name: '웃는 얼굴',
    size: 5,
    description: '초급 - 웃는 얼굴',
    solution: [
      [false, true, false, true, false],
      [false, false, false, false, false],
      [true, false, false, false, true],
      [false, true, true, true, false],
      [false, false, false, false, false],
    ],
  },
  {
    id: 'house-5x5',
    name: '집',
    size: 5,
    description: '초급 - 집',
    solution: [
      [false, false, true, false, false],
      [false, true, true, true, false],
      [true, true, true, true, true],
      [true, false, true, false, true],
      [true, true, true, true, true],
    ],
  },
  {
    id: 'arrow-5x5',
    name: '화살표',
    size: 5,
    description: '초급 - 오른쪽 화살표',
    solution: [
      [false, false, true, false, false],
      [false, true, true, true, false],
      [true, true, true, true, true],
      [false, true, true, true, false],
      [false, false, true, false, false],
    ],
  },
  {
    id: 'star-5x5',
    name: '별',
    size: 5,
    description: '초급 - 별',
    solution: [
      [false, false, true, false, false],
      [false, true, true, true, false],
      [true, true, true, true, true],
      [false, true, true, true, false],
      [false, true, false, true, false],
    ],
  },
  {
    id: 'cup-5x5',
    name: '컵',
    size: 5,
    description: '초급 - 컵',
    solution: [
      [true, false, false, false, true],
      [true, false, false, false, true],
      [true, true, true, true, true],
      [false, true, true, true, false],
      [false, true, true, true, false],
    ],
  },
  {
    id: 'moon-5x5',
    name: '달',
    size: 5,
    description: '초급 - 초승달',
    solution: [
      [false, false, true, true, false],
      [false, true, true, true, true],
      [true, true, true, true, false],
      [false, true, true, true, true],
      [false, false, true, true, false],
    ],
  },
  {
    id: 'cross-5x5',
    name: '십자가',
    size: 5,
    description: '초급 - 십자가',
    solution: [
      [false, false, true, false, false],
      [false, false, true, false, false],
      [true, true, true, true, true],
      [false, false, true, false, false],
      [false, false, true, false, false],
    ],
  },
  // ========== 중급 (10×10) ==========
  {
    id: 'butterfly-10x10',
    name: '나비',
    size: 10,
    description: '중급 - 나비',
    solution: [
      [false, false, false, true, true, true, true, false, false, false],
      [false, false, true, true, true, true, true, true, false, false],
      [false, true, true, false, true, true, false, true, true, false],
      [true, true, true, true, true, true, true, true, true, true],
      [true, true, true, true, true, true, true, true, true, true],
      [false, true, true, true, true, true, true, true, true, false],
      [false, false, true, true, true, true, true, true, false, false],
      [false, false, false, true, true, true, true, false, false, false],
      [false, false, false, false, true, true, false, false, false, false],
      [false, false, false, false, false, false, false, false, false, false],
    ],
  },
  {
    id: 'cat-10x10',
    name: '고양이',
    size: 10,
    description: '중급 - 고양이 얼굴',
    solution: [
      [false, false, true, true, true, true, true, true, false, false],
      [false, true, true, true, true, true, true, true, true, false],
      [true, true, false, true, true, true, true, false, true, true],
      [true, true, true, true, true, true, true, true, true, true],
      [true, true, false, true, true, true, true, false, true, true],
      [true, true, true, false, false, false, false, true, true, true],
      [false, true, true, true, true, true, true, true, true, false],
      [false, false, true, true, true, true, true, true, false, false],
      [false, false, false, true, true, true, true, false, false, false],
      [false, false, false, false, true, true, false, false, false, false],
    ],
  },
  {
    id: 'flower-10x10',
    name: '꽃',
    size: 10,
    description: '중급 - 꽃',
    solution: [
      [false, false, false, false, true, true, false, false, false, false],
      [false, false, false, true, true, true, true, false, false, false],
      [false, false, true, true, true, true, true, true, false, false],
      [false, true, true, false, true, true, false, true, true, false],
      [true, true, true, true, true, true, true, true, true, true],
      [true, true, true, true, true, true, true, true, true, true],
      [false, true, true, false, true, true, false, true, true, false],
      [false, false, true, true, true, true, true, true, false, false],
      [false, false, false, true, true, true, true, false, false, false],
      [false, false, false, false, true, true, false, false, false, false],
    ],
  },
  {
    id: 'tree-10x10',
    name: '나무',
    size: 10,
    description: '중급 - 크리스마스 트리',
    solution: [
      [false, false, false, false, true, true, false, false, false, false],
      [false, false, false, true, true, true, true, false, false, false],
      [false, false, true, true, true, true, true, true, false, false],
      [false, true, true, true, true, true, true, true, true, false],
      [true, true, true, true, true, true, true, true, true, true],
      [false, false, false, false, true, true, false, false, false, false],
      [false, false, false, false, true, true, false, false, false, false],
      [false, false, false, false, true, true, false, false, false, false],
      [false, false, false, true, true, true, true, false, false, false],
      [false, false, false, true, true, true, true, false, false, false],
    ],
  },
  {
    id: 'diamond-10x10',
    name: '다이아몬드',
    size: 10,
    description: '중급 - 다이아몬드',
    solution: [
      [false, false, false, false, true, true, false, false, false, false],
      [false, false, false, true, true, true, true, false, false, false],
      [false, false, true, true, true, true, true, true, false, false],
      [false, true, true, true, true, true, true, true, true, false],
      [true, true, true, true, true, true, true, true, true, true],
      [true, true, true, true, true, true, true, true, true, true],
      [false, true, true, true, true, true, true, true, true, false],
      [false, false, true, true, true, true, true, true, false, false],
      [false, false, false, true, true, true, true, false, false, false],
      [false, false, false, false, true, true, false, false, false, false],
    ],
  },
  {
    id: 'dog-10x10',
    name: '강아지',
    size: 10,
    description: '중급 - 강아지 얼굴',
    solution: [
      [false, false, true, true, true, true, true, true, false, false],
      [false, true, true, true, true, true, true, true, true, false],
      [true, true, false, true, true, true, true, false, true, true],
      [true, true, true, true, true, true, true, true, true, true],
      [true, true, false, true, true, true, true, false, true, true],
      [true, true, true, false, false, false, false, true, true, true],
      [false, true, true, true, false, false, true, true, true, false],
      [false, false, true, true, true, true, true, true, false, false],
      [false, false, false, true, true, true, true, false, false, false],
      [false, false, false, false, true, true, false, false, false, false],
    ],
  },
  {
    id: 'sun-10x10',
    name: '태양',
    size: 10,
    description: '중급 - 태양',
    solution: [
      [false, false, true, true, true, true, true, true, false, false],
      [false, true, true, true, true, true, true, true, true, false],
      [true, true, false, true, true, true, true, false, true, true],
      [true, true, true, false, true, true, false, true, true, true],
      [true, true, true, true, true, true, true, true, true, true],
      [true, true, true, true, true, true, true, true, true, true],
      [true, true, true, false, true, true, false, true, true, true],
      [true, true, false, true, true, true, true, false, true, true],
      [false, true, true, true, true, true, true, true, true, false],
      [false, false, true, true, true, true, true, true, false, false],
    ],
  },
  {
    id: 'car-10x10',
    name: '자동차',
    size: 10,
    description: '중급 - 자동차',
    solution: [
      [false, false, false, true, true, true, true, false, false, false],
      [false, false, true, true, true, true, true, true, false, false],
      [true, true, true, true, true, true, true, true, true, true],
      [true, true, false, true, true, true, true, false, true, true],
      [true, true, true, true, true, true, true, true, true, true],
      [false, true, true, true, true, true, true, true, true, false],
      [false, false, true, true, true, true, true, true, false, false],
      [false, false, true, true, false, false, true, true, false, false],
      [false, false, true, true, false, false, true, true, false, false],
      [false, false, true, true, true, true, true, true, false, false],
    ],
  },
  {
    id: 'boat-10x10',
    name: '배',
    size: 10,
    description: '중급 - 배',
    solution: [
      [false, false, false, false, true, true, false, false, false, false],
      [false, false, false, true, true, true, true, false, false, false],
      [false, false, true, true, true, true, true, true, false, false],
      [false, true, true, true, true, true, true, true, true, false],
      [true, true, true, true, true, true, true, true, true, true],
      [false, true, true, true, true, true, true, true, true, false],
      [false, false, true, true, true, true, true, true, false, false],
      [false, false, false, true, true, true, true, false, false, false],
      [false, false, false, false, true, true, false, false, false, false],
      [false, false, false, false, false, false, false, false, false, false],
    ],
  },
  {
    id: 'rabbit-10x10',
    name: '토끼',
    size: 10,
    description: '중급 - 토끼',
    solution: [
      [false, false, true, false, false, false, false, true, false, false],
      [false, true, true, true, false, false, true, true, true, false],
      [true, true, true, true, true, true, true, true, true, true],
      [true, true, false, true, true, true, true, false, true, true],
      [true, true, true, true, true, true, true, true, true, true],
      [false, true, true, true, false, false, true, true, true, false],
      [false, false, true, true, true, true, true, true, false, false],
      [false, false, false, true, true, true, true, false, false, false],
      [false, false, false, false, true, true, false, false, false, false],
      [false, false, false, false, false, false, false, false, false, false],
    ],
  },
  {
    id: 'penguin-10x10',
    name: '펭귄',
    size: 10,
    description: '중급 - 펭귄',
    solution: [
      [false, false, false, true, true, true, true, false, false, false],
      [false, false, true, true, true, true, true, true, false, false],
      [false, true, true, true, true, true, true, true, true, false],
      [true, true, false, true, true, true, true, false, true, true],
      [true, true, true, true, true, true, true, true, true, true],
      [true, true, true, true, true, true, true, true, true, true],
      [false, true, true, true, true, true, true, true, true, false],
      [false, false, true, true, true, true, true, true, false, false],
      [false, false, false, true, true, true, true, false, false, false],
      [false, false, false, false, true, true, false, false, false, false],
    ],
  },
  {
    id: 'owl-10x10',
    name: '부엉이',
    size: 10,
    description: '중급 - 부엉이',
    solution: [
      [false, false, true, true, true, true, true, true, false, false],
      [false, true, true, true, true, true, true, true, true, false],
      [true, true, false, true, true, true, true, false, true, true],
      [true, true, true, true, true, true, true, true, true, true],
      [true, true, false, true, true, true, true, false, true, true],
      [true, true, true, false, false, false, false, true, true, true],
      [false, true, true, true, true, true, true, true, true, false],
      [false, false, true, true, true, true, true, true, false, false],
      [false, false, false, true, true, true, true, false, false, false],
      [false, false, false, false, true, true, false, false, false, false],
    ],
  },
  {
    id: 'duck-10x10',
    name: '오리',
    size: 10,
    description: '중급 - 오리',
    solution: [
      [false, false, false, false, true, true, false, false, false, false],
      [false, false, false, true, true, true, true, false, false, false],
      [false, false, true, true, true, true, true, true, false, false],
      [false, true, true, true, true, true, true, true, true, false],
      [true, true, true, true, true, true, true, true, true, true],
      [false, true, true, true, true, true, true, true, true, false],
      [false, false, true, true, true, true, true, true, false, false],
      [false, false, false, true, true, true, true, false, false, false],
      [false, false, false, false, true, true, false, false, false, false],
      [false, false, false, false, false, false, false, false, false, false],
    ],
  },
  {
    id: 'bear-10x10',
    name: '곰',
    size: 10,
    description: '중급 - 곰 얼굴',
    solution: [
      [false, false, true, true, true, true, true, true, false, false],
      [false, true, true, true, true, true, true, true, true, false],
      [true, true, false, true, true, true, true, false, true, true],
      [true, true, true, true, true, true, true, true, true, true],
      [true, true, false, true, true, true, true, false, true, true],
      [true, true, true, false, true, true, false, true, true, true],
      [false, true, true, true, false, false, true, true, true, false],
      [false, false, true, true, true, true, true, true, false, false],
      [false, false, false, true, true, true, true, false, false, false],
      [false, false, false, false, true, true, false, false, false, false],
    ],
  },
  {
    id: 'panda-10x10',
    name: '판다',
    size: 10,
    description: '중급 - 판다 얼굴',
    solution: [
      [false, false, true, true, true, true, true, true, false, false],
      [false, true, true, true, true, true, true, true, true, false],
      [true, true, false, false, true, true, false, false, true, true],
      [true, true, false, false, true, true, false, false, true, true],
      [true, true, true, true, true, true, true, true, true, true],
      [true, true, true, true, false, false, true, true, true, true],
      [false, true, true, true, true, true, true, true, true, false],
      [false, false, true, true, true, true, true, true, false, false],
      [false, false, false, true, true, true, true, false, false, false],
      [false, false, false, false, true, true, false, false, false, false],
    ],
  },
  {
    id: 'turtle-10x10',
    name: '거북이',
    size: 10,
    description: '중급 - 거북이',
    solution: [
      [false, false, false, false, true, true, false, false, false, false],
      [false, false, false, true, true, true, true, false, false, false],
      [false, false, true, true, true, true, true, true, false, false],
      [false, true, true, true, true, true, true, true, true, false],
      [true, true, true, true, true, true, true, true, true, true],
      [true, true, true, true, true, true, true, true, true, true],
      [false, true, true, true, true, true, true, true, true, false],
      [false, false, true, true, true, true, true, true, false, false],
      [false, false, false, true, true, true, true, false, false, false],
      [false, false, false, false, true, true, false, false, false, false],
    ],
  },
  {
    id: 'snail-10x10',
    name: '달팽이',
    size: 10,
    description: '중급 - 달팽이',
    solution: [
      [false, false, false, false, false, false, true, true, false, false],
      [false, false, false, false, false, true, true, true, true, false],
      [false, false, false, false, true, true, true, true, true, true],
      [false, false, false, true, true, true, true, true, true, true],
      [false, false, true, true, true, true, true, true, true, true],
      [false, true, true, true, true, true, true, true, true, true],
      [true, true, true, true, true, true, true, true, true, true],
      [false, true, true, true, true, true, true, true, true, false],
      [false, false, true, true, true, true, true, true, false, false],
      [false, false, false, true, true, true, true, false, false, false],
    ],
  },
  {
    id: 'butterfly2-10x10',
    name: '나비 2',
    size: 10,
    description: '중급 - 나비 (다른 모양)',
    solution: [
      [false, false, true, true, false, false, true, true, false, false],
      [false, true, true, true, true, true, true, true, true, false],
      [true, true, true, true, true, true, true, true, true, true],
      [true, true, false, true, true, true, true, false, true, true],
      [true, true, true, true, true, true, true, true, true, true],
      [true, true, true, true, true, true, true, true, true, true],
      [true, true, false, true, true, true, true, false, true, true],
      [true, true, true, true, true, true, true, true, true, true],
      [false, true, true, true, true, true, true, true, true, false],
      [false, false, true, true, false, false, true, true, false, false],
    ],
  },
  {
    id: 'house2-10x10',
    name: '집 2',
    size: 10,
    description: '중급 - 집 (큰 집)',
    solution: [
      [false, false, false, false, true, true, false, false, false, false],
      [false, false, false, true, true, true, true, false, false, false],
      [false, false, true, true, true, true, true, true, false, false],
      [false, true, true, true, true, true, true, true, true, false],
      [true, true, true, true, true, true, true, true, true, true],
      [true, true, false, true, true, true, true, false, true, true],
      [true, true, true, true, true, true, true, true, true, true],
      [true, true, false, true, true, true, true, false, true, true],
      [true, true, true, true, true, true, true, true, true, true],
      [true, true, true, true, true, true, true, true, true, true],
    ],
  },
  {
    id: 'castle-10x10',
    name: '성',
    size: 10,
    description: '중급 - 성',
    solution: [
      [false, false, true, true, true, true, true, true, false, false],
      [false, true, true, true, true, true, true, true, true, false],
      [true, true, true, true, true, true, true, true, true, true],
      [true, true, false, true, true, true, true, false, true, true],
      [true, true, true, true, true, true, true, true, true, true],
      [true, true, true, true, true, true, true, true, true, true],
      [true, true, false, true, true, true, true, false, true, true],
      [true, true, true, true, true, true, true, true, true, true],
      [true, true, true, true, true, true, true, true, true, true],
      [true, true, true, true, true, true, true, true, true, true],
    ],
  },
  {
    id: 'mountain-10x10',
    name: '산',
    size: 10,
    description: '중급 - 산',
    solution: [
      [false, false, false, false, false, true, true, false, false, false],
      [false, false, false, false, true, true, true, true, false, false],
      [false, false, false, true, true, true, true, true, true, false],
      [false, false, true, true, true, true, true, true, true, true],
      [false, true, true, true, true, true, true, true, true, true],
      [true, true, true, true, true, true, true, true, true, true],
      [false, true, true, true, true, true, true, true, true, false],
      [false, false, true, true, true, true, true, true, false, false],
      [false, false, false, true, true, true, true, false, false, false],
      [false, false, false, false, true, true, false, false, false, false],
    ],
  },
  {
    id: 'heart2-10x10',
    name: '하트 2',
    size: 10,
    description: '중급 - 큰 하트',
    solution: [
      [false, false, true, true, false, false, true, true, false, false],
      [false, true, true, true, true, true, true, true, true, false],
      [true, true, true, true, true, true, true, true, true, true],
      [true, true, true, true, true, true, true, true, true, true],
      [false, true, true, true, true, true, true, true, true, false],
      [false, false, true, true, true, true, true, true, false, false],
      [false, false, false, true, true, true, true, false, false, false],
      [false, false, false, false, true, true, false, false, false, false],
      [false, false, false, false, false, false, false, false, false, false],
      [false, false, false, false, false, false, false, false, false, false],
    ],
  },
  {
    id: 'star2-10x10',
    name: '별 2',
    size: 10,
    description: '중급 - 큰 별',
    solution: [
      [false, false, false, false, true, true, false, false, false, false],
      [false, false, false, true, true, true, true, false, false, false],
      [false, false, true, true, true, true, true, true, false, false],
      [false, true, true, false, true, true, false, true, true, false],
      [true, true, true, true, true, true, true, true, true, true],
      [true, true, true, true, true, true, true, true, true, true],
      [false, true, true, false, true, true, false, true, true, false],
      [false, false, true, true, true, true, true, true, false, false],
      [false, false, false, true, true, true, true, false, false, false],
      [false, false, false, false, true, true, false, false, false, false],
    ],
  },
  // ========== 고급 (15×15) ==========
  {
    id: 'bird-15x15',
    name: '새',
    size: 15,
    description: '고급 - 새',
    solution: [
      [false, false, false, false, false, false, true, true, false, false, false, false, false, false, false],
      [false, false, false, false, false, true, true, true, true, false, false, false, false, false, false],
      [false, false, false, false, true, true, true, true, true, true, false, false, false, false, false],
      [false, false, false, true, true, true, true, true, true, true, true, false, false, false, false],
      [false, false, true, true, true, true, true, true, true, true, true, true, false, false, false],
      [false, true, true, true, true, true, true, true, true, true, true, true, true, false, false],
      [true, true, true, true, true, true, true, true, true, true, true, true, true, true, false],
      [true, true, true, true, true, true, true, true, true, true, true, true, true, true, true],
      [false, true, true, true, true, true, true, true, true, true, true, true, true, true, false],
      [false, false, true, true, true, true, true, true, true, true, true, true, true, false, false],
      [false, false, false, true, true, true, true, true, true, true, true, true, false, false, false],
      [false, false, false, false, true, true, true, true, true, true, true, false, false, false, false],
      [false, false, false, false, false, true, true, true, true, true, false, false, false, false, false],
      [false, false, false, false, false, false, true, true, true, false, false, false, false, false, false],
      [false, false, false, false, false, false, false, true, false, false, false, false, false, false, false],
    ],
  },
  {
    id: 'fish-15x15',
    name: '물고기',
    size: 15,
    description: '고급 - 물고기',
    solution: [
      [false, false, false, false, false, true, true, true, false, false, false, false, false, false, false],
      [false, false, false, false, true, true, true, true, true, false, false, false, false, false, false],
      [false, false, false, true, true, true, true, true, true, true, false, false, false, false, false],
      [false, false, true, true, true, true, true, true, true, true, true, false, false, false, false],
      [false, true, true, true, true, true, true, true, true, true, true, true, false, false, false],
      [true, true, true, true, true, true, true, true, true, true, true, true, true, false, false],
      [true, true, true, true, true, true, true, true, true, true, true, true, true, true, false],
      [true, true, true, true, true, true, true, true, true, true, true, true, true, true, true],
      [true, true, true, true, true, true, true, true, true, true, true, true, true, true, false],
      [false, true, true, true, true, true, true, true, true, true, true, true, true, false, false],
      [false, false, true, true, true, true, true, true, true, true, true, true, false, false, false],
      [false, false, false, true, true, true, true, true, true, true, true, false, false, false, false],
      [false, false, false, false, true, true, true, true, true, true, false, false, false, false, false],
      [false, false, false, false, false, true, true, true, true, false, false, false, false, false, false],
      [false, false, false, false, false, false, true, true, false, false, false, false, false, false, false],
    ],
  },
  {
    id: 'airplane-15x15',
    name: '비행기',
    size: 15,
    description: '고급 - 비행기',
    solution: [
      [false, false, false, false, false, false, false, true, false, false, false, false, false, false, false],
      [false, false, false, false, false, false, true, true, true, false, false, false, false, false, false],
      [false, false, false, false, false, true, true, true, true, true, false, false, false, false, false],
      [false, false, false, false, true, true, true, true, true, true, true, false, false, false, false],
      [false, false, false, true, true, true, true, true, true, true, true, true, false, false, false],
      [false, false, true, true, true, true, true, true, true, true, true, true, true, false, false],
      [false, true, true, true, true, true, true, true, true, true, true, true, true, true, false],
      [true, true, true, true, true, true, true, true, true, true, true, true, true, true, true],
      [false, true, true, true, true, true, true, true, true, true, true, true, true, true, false],
      [false, false, true, true, true, true, true, true, true, true, true, true, true, false, false],
      [false, false, false, true, true, true, true, true, true, true, true, true, false, false, false],
      [false, false, false, false, true, true, true, true, true, true, true, false, false, false, false],
      [false, false, false, false, false, true, true, true, true, true, false, false, false, false, false],
      [false, false, false, false, false, false, true, true, true, false, false, false, false, false, false],
      [false, false, false, false, false, false, false, true, false, false, false, false, false, false, false],
    ],
  },
  {
    id: 'elephant-15x15',
    name: '코끼리',
    size: 15,
    description: '고급 - 코끼리',
    solution: [
      [false, false, false, false, true, true, true, true, true, false, false, false, false, false, false],
      [false, false, false, true, true, true, true, true, true, true, false, false, false, false, false],
      [false, false, true, true, true, true, true, true, true, true, true, false, false, false, false],
      [false, true, true, true, false, true, true, true, false, true, true, true, false, false, false],
      [true, true, true, true, true, true, true, true, true, true, true, true, true, false, false],
      [true, true, true, true, true, true, true, true, true, true, true, true, true, true, false],
      [true, true, true, true, true, true, true, true, true, true, true, true, true, true, true],
      [true, true, true, true, true, true, true, true, true, true, true, true, true, true, true],
      [false, true, true, true, true, true, true, true, true, true, true, true, true, true, false],
      [false, false, true, true, true, true, true, true, true, true, true, true, true, false, false],
      [false, false, false, true, true, true, true, true, true, true, true, true, false, false, false],
      [false, false, false, false, true, true, true, true, true, true, true, false, false, false, false],
      [false, false, false, false, false, true, true, true, true, true, false, false, false, false, false],
      [false, false, false, false, false, false, true, true, true, false, false, false, false, false, false],
      [false, false, false, false, false, false, false, true, false, false, false, false, false, false, false],
    ],
  },
  {
    id: 'lion-15x15',
    name: '사자',
    size: 15,
    description: '고급 - 사자',
    solution: [
      [false, false, false, false, true, true, true, true, true, false, false, false, false, false, false],
      [false, false, false, true, true, true, true, true, true, true, false, false, false, false, false],
      [false, false, true, true, true, true, true, true, true, true, true, false, false, false, false],
      [false, true, true, false, true, true, true, true, true, false, true, true, false, false, false],
      [true, true, true, true, true, true, true, true, true, true, true, true, true, false, false],
      [true, true, true, true, true, true, true, true, true, true, true, true, true, true, false],
      [true, true, false, true, true, true, true, true, true, true, false, true, true, true, false],
      [true, true, true, true, true, true, true, true, true, true, true, true, true, true, true],
      [true, true, true, false, true, true, true, true, true, false, true, true, true, true, false],
      [false, true, true, true, true, true, true, true, true, true, true, true, true, false, false],
      [false, false, true, true, true, true, true, true, true, true, true, true, false, false, false],
      [false, false, false, true, true, true, true, true, true, true, true, false, false, false, false],
      [false, false, false, false, true, true, true, true, true, true, false, false, false, false, false],
      [false, false, false, false, false, true, true, true, true, false, false, false, false, false, false],
      [false, false, false, false, false, false, true, true, false, false, false, false, false, false, false],
    ],
  },
  {
    id: 'cat-15x15',
    name: '고양이',
    size: 15,
    description: '고급 - 고양이',
    solution: [
      [false, false, false, false, true, true, true, true, true, false, false, false, false, false, false],
      [false, false, false, true, true, true, true, true, true, true, false, false, false, false, false],
      [false, false, true, true, true, true, true, true, true, true, true, false, false, false, false],
      [false, true, true, false, true, true, true, true, true, false, true, true, false, false, false],
      [true, true, true, true, true, true, true, true, true, true, true, true, true, false, false],
      [true, true, true, true, true, true, true, true, true, true, true, true, true, true, false],
      [true, true, false, true, true, true, true, true, true, true, false, true, true, true, false],
      [true, true, true, true, true, true, true, true, true, true, true, true, true, true, true],
      [true, true, false, true, true, true, true, true, true, true, false, true, true, true, false],
      [false, true, true, true, false, false, false, false, false, true, true, true, true, false, false],
      [false, false, true, true, true, true, true, true, true, true, true, true, false, false, false],
      [false, false, false, true, true, true, true, true, true, true, true, false, false, false, false],
      [false, false, false, false, true, true, true, true, true, true, false, false, false, false, false],
      [false, false, false, false, false, true, true, true, true, false, false, false, false, false, false],
      [false, false, false, false, false, false, true, true, false, false, false, false, false, false, false],
    ],
  },
  {
    id: 'dog-15x15',
    name: '강아지',
    size: 15,
    description: '고급 - 강아지',
    solution: [
      [false, false, false, false, true, true, true, true, true, false, false, false, false, false, false],
      [false, false, false, true, true, true, true, true, true, true, false, false, false, false, false],
      [false, false, true, true, true, true, true, true, true, true, true, false, false, false, false],
      [false, true, true, false, true, true, true, true, true, false, true, true, false, false, false],
      [true, true, true, true, true, true, true, true, true, true, true, true, true, false, false],
      [true, true, true, true, true, true, true, true, true, true, true, true, true, true, false],
      [true, true, false, true, true, true, true, true, true, true, false, true, true, true, false],
      [true, true, true, true, true, true, true, true, true, true, true, true, true, true, true],
      [true, true, true, false, false, false, false, false, false, true, true, true, true, true, false],
      [false, true, true, true, true, true, true, true, true, true, true, true, true, false, false],
      [false, false, true, true, true, true, true, true, true, true, true, true, false, false, false],
      [false, false, false, true, true, true, true, true, true, true, true, false, false, false, false],
      [false, false, false, false, true, true, true, true, true, true, false, false, false, false, false],
      [false, false, false, false, false, true, true, true, true, false, false, false, false, false, false],
      [false, false, false, false, false, false, true, true, false, false, false, false, false, false, false],
    ],
  },
  {
    id: 'butterfly-15x15',
    name: '나비',
    size: 15,
    description: '고급 - 나비',
    solution: [
      [false, false, false, true, true, true, true, true, true, true, true, false, false, false, false],
      [false, false, true, true, true, true, true, true, true, true, true, true, false, false, false],
      [false, true, true, false, true, true, true, true, true, true, false, true, true, false, false],
      [true, true, true, true, true, true, true, true, true, true, true, true, true, true, false],
      [true, true, true, true, true, true, true, true, true, true, true, true, true, true, true],
      [true, true, true, true, true, true, true, true, true, true, true, true, true, true, true],
      [false, true, true, true, true, true, true, true, true, true, true, true, true, true, false],
      [false, false, true, true, true, true, true, true, true, true, true, true, true, false, false],
      [false, false, false, true, true, true, true, true, true, true, true, true, false, false, false],
      [false, false, true, true, true, true, true, true, true, true, true, true, true, false, false],
      [false, true, true, true, true, true, true, true, true, true, true, true, true, true, false],
      [true, true, true, true, true, true, true, true, true, true, true, true, true, true, true],
      [true, true, true, true, true, true, true, true, true, true, true, true, true, true, true],
      [false, true, true, false, true, true, true, true, true, true, false, true, true, false, false],
      [false, false, true, true, true, true, true, true, true, true, true, true, false, false, false],
    ],
  },
  {
    id: 'flower-15x15',
    name: '꽃',
    size: 15,
    description: '고급 - 꽃',
    solution: [
      [false, false, false, false, false, false, true, true, false, false, false, false, false, false, false],
      [false, false, false, false, false, true, true, true, true, false, false, false, false, false, false],
      [false, false, false, false, true, true, true, true, true, true, false, false, false, false, false],
      [false, false, false, true, true, false, true, true, false, true, true, false, false, false, false],
      [false, false, true, true, true, true, true, true, true, true, true, true, false, false, false],
      [false, true, true, true, true, true, true, true, true, true, true, true, true, false, false],
      [true, true, true, false, true, true, true, true, true, true, false, true, true, true, false],
      [true, true, true, true, true, true, true, true, true, true, true, true, true, true, true],
      [true, true, true, false, true, true, true, true, true, true, false, true, true, true, false],
      [false, true, true, true, true, true, true, true, true, true, true, true, true, false, false],
      [false, false, true, true, true, true, true, true, true, true, true, true, false, false, false],
      [false, false, false, true, true, false, true, true, false, true, true, false, false, false, false],
      [false, false, false, false, true, true, true, true, true, true, false, false, false, false, false],
      [false, false, false, false, false, true, true, true, true, false, false, false, false, false, false],
      [false, false, false, false, false, false, true, true, false, false, false, false, false, false, false],
    ],
  },
  {
    id: 'tree-15x15',
    name: '나무',
    size: 15,
    description: '고급 - 크리스마스 트리',
    solution: [
      [false, false, false, false, false, false, true, true, false, false, false, false, false, false, false],
      [false, false, false, false, false, true, true, true, true, false, false, false, false, false, false],
      [false, false, false, false, true, true, true, true, true, true, false, false, false, false, false],
      [false, false, false, true, true, true, true, true, true, true, true, false, false, false, false],
      [false, false, true, true, true, true, true, true, true, true, true, true, false, false, false],
      [false, true, true, true, true, true, true, true, true, true, true, true, true, false, false],
      [true, true, true, true, true, true, true, true, true, true, true, true, true, true, false],
      [false, false, false, false, false, false, true, true, false, false, false, false, false, false, false],
      [false, false, false, false, false, false, true, true, false, false, false, false, false, false, false],
      [false, false, false, false, false, false, true, true, false, false, false, false, false, false, false],
      [false, false, false, false, false, true, true, true, true, false, false, false, false, false, false],
      [false, false, false, false, false, true, true, true, true, false, false, false, false, false, false],
      [false, false, false, false, true, true, true, true, true, true, false, false, false, false, false],
      [false, false, false, false, true, true, true, true, true, true, false, false, false, false, false],
      [false, false, false, false, true, true, true, true, true, true, false, false, false, false, false],
    ],
  },
  {
    id: 'house-15x15',
    name: '집',
    size: 15,
    description: '고급 - 집',
    solution: [
      [false, false, false, false, false, false, true, true, false, false, false, false, false, false, false],
      [false, false, false, false, false, true, true, true, true, false, false, false, false, false, false],
      [false, false, false, false, true, true, true, true, true, true, false, false, false, false, false],
      [false, false, false, true, true, true, true, true, true, true, true, false, false, false, false],
      [false, false, true, true, true, true, true, true, true, true, true, true, false, false, false],
      [false, true, true, true, true, true, true, true, true, true, true, true, true, false, false],
      [true, true, true, true, true, true, true, true, true, true, true, true, true, true, false],
      [true, true, false, true, true, true, true, true, true, true, false, true, true, true, false],
      [true, true, true, true, true, true, true, true, true, true, true, true, true, true, true],
      [true, true, false, true, true, true, true, true, true, true, false, true, true, true, false],
      [true, true, true, true, true, true, true, true, true, true, true, true, true, true, true],
      [true, true, false, true, true, true, true, true, true, true, false, true, true, true, false],
      [true, true, true, true, true, true, true, true, true, true, true, true, true, true, true],
      [true, true, true, true, true, true, true, true, true, true, true, true, true, true, true],
      [true, true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    ],
  },
  {
    id: 'castle-15x15',
    name: '성',
    size: 15,
    description: '고급 - 성',
    solution: [
      [false, false, true, true, true, true, true, true, true, true, true, true, true, false, false],
      [false, true, true, true, true, true, true, true, true, true, true, true, true, true, false],
      [true, true, true, true, true, true, true, true, true, true, true, true, true, true, true],
      [true, true, false, true, true, true, true, true, true, true, false, true, true, true, false],
      [true, true, true, true, true, true, true, true, true, true, true, true, true, true, true],
      [true, true, true, true, true, true, true, true, true, true, true, true, true, true, true],
      [true, true, false, true, true, true, true, true, true, true, false, true, true, true, false],
      [true, true, true, true, true, true, true, true, true, true, true, true, true, true, true],
      [true, true, true, true, true, true, true, true, true, true, true, true, true, true, true],
      [true, true, false, true, true, true, true, true, true, true, false, true, true, true, false],
      [true, true, true, true, true, true, true, true, true, true, true, true, true, true, true],
      [true, true, true, true, true, true, true, true, true, true, true, true, true, true, true],
      [true, true, true, true, true, true, true, true, true, true, true, true, true, true, true],
      [true, true, true, true, true, true, true, true, true, true, true, true, true, true, true],
      [true, true, true, true, true, true, true, true, true, true, true, true, true, true, true],
    ],
  },
  {
    id: 'ship-15x15',
    name: '배',
    size: 15,
    description: '고급 - 배',
    solution: [
      [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false],
      [false, false, false, false, false, false, false, true, false, false, false, false, false, false, false],
      [false, false, false, false, false, false, true, true, true, false, false, false, false, false, false],
      [false, false, false, false, false, true, true, true, true, true, false, false, false, false, false],
      [false, false, false, false, true, true, true, true, true, true, true, false, false, false, false],
      [false, false, false, true, true, true, true, true, true, true, true, true, false, false, false],
      [false, false, true, true, true, true, true, true, true, true, true, true, true, false, false],
      [false, true, true, true, true, true, true, true, true, true, true, true, true, true, false],
      [true, true, true, true, true, true, true, true, true, true, true, true, true, true, true],
      [false, true, true, true, true, true, true, true, true, true, true, true, true, true, false],
      [false, false, true, true, true, true, true, true, true, true, true, true, true, false, false],
      [false, false, false, true, true, true, true, true, true, true, true, true, false, false, false],
      [false, false, false, false, true, true, true, true, true, true, true, false, false, false, false],
      [false, false, false, false, false, true, true, true, true, true, false, false, false, false, false],
      [false, false, false, false, false, false, true, true, true, false, false, false, false, false, false],
    ],
  },
  {
    id: 'car-15x15',
    name: '자동차',
    size: 15,
    description: '고급 - 자동차',
    solution: [
      [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false],
      [false, false, false, false, false, true, true, true, true, true, false, false, false, false, false],
      [false, false, false, false, true, true, true, true, true, true, true, false, false, false, false],
      [false, false, true, true, true, true, true, true, true, true, true, true, true, false, false],
      [true, true, true, true, true, true, true, true, true, true, true, true, true, true, false],
      [true, true, false, true, true, true, true, true, true, true, false, true, true, true, false],
      [true, true, true, true, true, true, true, true, true, true, true, true, true, true, true],
      [false, true, true, true, true, true, true, true, true, true, true, true, true, true, false],
      [false, false, true, true, true, true, true, true, true, true, true, true, true, false, false],
      [false, false, true, true, false, false, false, false, false, false, true, true, false, false, false],
      [false, false, true, true, false, false, false, false, false, false, true, true, false, false, false],
      [false, false, true, true, false, false, false, false, false, false, true, true, false, false, false],
      [false, false, true, true, true, true, true, true, true, true, true, true, false, false, false],
      [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false],
      [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    ],
  },
  {
    id: 'robot-15x15',
    name: '로봇',
    size: 15,
    description: '고급 - 로봇',
    solution: [
      [false, false, false, false, true, true, true, true, true, false, false, false, false, false, false],
      [false, false, false, true, true, true, true, true, true, true, false, false, false, false, false],
      [false, false, true, true, true, true, true, true, true, true, true, false, false, false, false],
      [false, true, true, false, true, true, true, true, true, false, true, true, false, false, false],
      [true, true, true, true, true, true, true, true, true, true, true, true, true, false, false],
      [true, true, false, true, true, true, true, true, true, true, false, true, true, true, false],
      [true, true, true, true, true, true, true, true, true, true, true, true, true, true, true],
      [true, true, true, false, false, false, false, false, false, false, true, true, true, true, false],
      [true, true, true, true, true, true, true, true, true, true, true, true, true, true, true],
      [true, true, false, true, true, true, true, true, true, true, false, true, true, true, false],
      [true, true, true, true, true, true, true, true, true, true, true, true, true, false, false],
      [false, true, true, false, true, true, true, true, true, false, true, true, false, false, false],
      [false, false, true, true, true, true, true, true, true, true, true, false, false, false, false],
      [false, false, false, true, true, true, true, true, true, true, false, false, false, false, false],
      [false, false, false, false, true, true, true, true, true, false, false, false, false, false, false],
    ],
  },
  {
    id: 'heart-15x15',
    name: '하트',
    size: 15,
    description: '고급 - 하트',
    solution: [
      [false, false, false, true, true, false, false, false, false, false, true, true, false, false, false],
      [false, false, true, true, true, true, false, false, false, true, true, true, true, false, false],
      [false, true, true, true, true, true, true, false, true, true, true, true, true, true, false],
      [true, true, true, true, true, true, true, true, true, true, true, true, true, true, true],
      [true, true, true, true, true, true, true, true, true, true, true, true, true, true, true],
      [true, true, true, true, true, true, true, true, true, true, true, true, true, true, true],
      [false, true, true, true, true, true, true, true, true, true, true, true, true, true, false],
      [false, false, true, true, true, true, true, true, true, true, true, true, true, false, false],
      [false, false, false, true, true, true, true, true, true, true, true, true, false, false, false],
      [false, false, false, false, true, true, true, true, true, true, true, false, false, false, false],
      [false, false, false, false, false, true, true, true, true, true, false, false, false, false, false],
      [false, false, false, false, false, false, true, true, true, false, false, false, false, false, false],
      [false, false, false, false, false, false, false, true, false, false, false, false, false, false, false],
      [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false],
      [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    ],
  },
  {
    id: 'star-15x15',
    name: '별',
    size: 15,
    description: '고급 - 별',
    solution: [
      [false, false, false, false, false, false, true, false, false, false, false, false, false, false, false],
      [false, false, false, false, false, true, true, true, false, false, false, false, false, false, false],
      [false, false, false, false, true, true, true, true, true, false, false, false, false, false, false],
      [false, false, false, true, true, false, true, false, true, true, false, false, false, false, false],
      [false, false, true, true, true, true, true, true, true, true, true, false, false, false, false],
      [false, true, true, true, true, true, true, true, true, true, true, true, false, false, false],
      [true, true, true, true, true, true, true, true, true, true, true, true, true, false, false],
      [false, true, true, true, true, true, true, true, true, true, true, true, false, false, false],
      [false, false, true, true, true, true, true, true, true, true, true, false, false, false, false],
      [false, false, false, true, true, false, true, false, true, true, false, false, false, false, false],
      [false, false, false, false, true, true, true, true, true, false, false, false, false, false, false],
      [false, false, false, false, false, true, true, true, false, false, false, false, false, false, false],
      [false, false, false, false, false, false, true, false, false, false, false, false, false, false, false],
      [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false],
      [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    ],
  },
  {
    id: 'moon-15x15',
    name: '달',
    size: 15,
    description: '고급 - 초승달',
    solution: [
      [false, false, false, false, false, false, true, true, true, true, false, false, false, false, false],
      [false, false, false, false, false, true, true, true, true, true, true, false, false, false, false],
      [false, false, false, false, true, true, true, true, true, true, true, true, false, false, false],
      [false, false, false, true, true, true, true, true, true, true, true, true, true, false, false],
      [false, false, true, true, true, true, true, true, true, true, true, true, true, true, false],
      [false, true, true, true, true, true, true, true, true, true, true, true, true, true, true],
      [true, true, true, true, true, true, true, true, true, true, true, true, true, true, true],
      [false, true, true, true, true, true, true, true, true, true, true, true, true, true, true],
      [false, false, true, true, true, true, true, true, true, true, true, true, true, true, false],
      [false, false, false, true, true, true, true, true, true, true, true, true, true, false, false],
      [false, false, false, false, true, true, true, true, true, true, true, true, false, false, false],
      [false, false, false, false, false, true, true, true, true, true, true, false, false, false, false],
      [false, false, false, false, false, false, true, true, true, true, false, false, false, false, false],
      [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false],
      [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    ],
  },
  {
    id: 'sun-15x15',
    name: '태양',
    size: 15,
    description: '고급 - 태양',
    solution: [
      [false, false, false, false, true, false, false, false, false, false, true, false, false, false, false],
      [false, false, false, true, true, true, false, false, false, true, true, true, false, false, false],
      [false, false, true, true, false, true, true, false, true, true, false, true, true, false, false],
      [false, true, true, true, true, true, true, true, true, true, true, true, true, true, false],
      [true, true, true, false, true, true, true, true, true, true, true, false, true, true, true],
      [false, true, true, true, true, true, true, true, true, true, true, true, true, true, false],
      [false, false, true, true, true, true, true, true, true, true, true, true, true, false, false],
      [true, true, true, true, true, true, true, true, true, true, true, true, true, true, true],
      [false, false, true, true, true, true, true, true, true, true, true, true, true, false, false],
      [false, true, true, true, true, true, true, true, true, true, true, true, true, true, false],
      [true, true, true, false, true, true, true, true, true, true, true, false, true, true, true],
      [false, true, true, true, true, true, true, true, true, true, true, true, true, true, false],
      [false, false, true, true, false, true, true, false, true, true, false, true, true, false, false],
      [false, false, false, true, true, true, false, false, false, true, true, true, false, false, false],
      [false, false, false, false, true, false, false, false, false, false, true, false, false, false, false],
    ],
  },
  {
    id: 'penguin-15x15',
    name: '펭귄',
    size: 15,
    description: '고급 - 펭귄',
    solution: [
      [false, false, false, false, false, true, true, true, true, false, false, false, false, false, false],
      [false, false, false, false, true, true, true, true, true, true, false, false, false, false, false],
      [false, false, false, true, true, true, true, true, true, true, true, false, false, false, false],
      [false, false, true, true, true, true, true, true, true, true, true, true, false, false, false],
      [false, true, true, false, true, true, true, true, true, true, false, true, true, false, false],
      [true, true, true, true, true, true, true, true, true, true, true, true, true, true, false],
      [true, true, true, true, true, true, true, true, true, true, true, true, true, true, true],
      [true, true, true, true, true, true, true, true, true, true, true, true, true, true, true],
      [false, true, true, true, true, true, true, true, true, true, true, true, true, true, false],
      [false, false, true, true, true, true, true, true, true, true, true, true, true, false, false],
      [false, false, false, true, true, true, true, true, true, true, true, true, false, false, false],
      [false, false, false, false, true, true, true, true, true, true, true, false, false, false, false],
      [false, false, false, false, false, true, true, true, true, true, false, false, false, false, false],
      [false, false, false, false, false, false, true, true, true, false, false, false, false, false, false],
      [false, false, false, false, false, false, false, true, false, false, false, false, false, false, false],
    ],
  },
  {
    id: 'owl-15x15',
    name: '부엉이',
    size: 15,
    description: '고급 - 부엉이',
    solution: [
      [false, false, false, false, true, true, true, true, true, false, false, false, false, false, false],
      [false, false, false, true, true, true, true, true, true, true, false, false, false, false, false],
      [false, false, true, true, true, true, true, true, true, true, true, false, false, false, false],
      [false, true, true, false, true, true, true, true, true, false, true, true, false, false, false],
      [true, true, true, true, true, true, true, true, true, true, true, true, true, false, false],
      [true, true, false, true, true, true, true, true, true, true, false, true, true, true, false],
      [true, true, true, true, true, true, true, true, true, true, true, true, true, true, true],
      [true, true, false, true, true, true, true, true, true, true, false, true, true, true, false],
      [true, true, true, false, false, false, false, false, false, true, true, true, true, true, false],
      [false, true, true, true, true, true, true, true, true, true, true, true, true, false, false],
      [false, false, true, true, true, true, true, true, true, true, true, true, false, false, false],
      [false, false, false, true, true, true, true, true, true, true, true, false, false, false, false],
      [false, false, false, false, true, true, true, true, true, true, false, false, false, false, false],
      [false, false, false, false, false, true, true, true, true, false, false, false, false, false, false],
      [false, false, false, false, false, false, true, true, false, false, false, false, false, false, false],
    ],
  },
  {
    id: 'bear-15x15',
    name: '곰',
    size: 15,
    description: '고급 - 곰',
    solution: [
      [false, false, false, false, true, true, true, true, true, false, false, false, false, false, false],
      [false, false, false, true, true, true, true, true, true, true, false, false, false, false, false],
      [false, false, true, true, true, true, true, true, true, true, true, false, false, false, false],
      [false, true, true, false, true, true, true, true, true, false, true, true, false, false, false],
      [true, true, true, true, true, true, true, true, true, true, true, true, true, false, false],
      [true, true, false, true, true, true, true, true, true, true, false, true, true, true, false],
      [true, true, true, true, true, true, true, true, true, true, true, true, true, true, true],
      [true, true, false, true, true, true, true, true, true, true, false, true, true, true, false],
      [true, true, true, false, true, true, false, false, true, true, false, true, true, true, false],
      [false, true, true, true, false, false, true, true, false, false, true, true, true, false, false],
      [false, false, true, true, true, true, true, true, true, true, true, true, false, false, false],
      [false, false, false, true, true, true, true, true, true, true, true, false, false, false, false],
      [false, false, false, false, true, true, true, true, true, true, false, false, false, false, false],
      [false, false, false, false, false, true, true, true, true, false, false, false, false, false, false],
      [false, false, false, false, false, false, true, true, false, false, false, false, false, false, false],
    ],
  },
  {
    id: 'panda-15x15',
    name: '판다',
    size: 15,
    description: '고급 - 판다',
    solution: [
      [false, false, false, false, true, true, true, true, true, false, false, false, false, false, false],
      [false, false, false, true, true, true, true, true, true, true, false, false, false, false, false],
      [false, false, true, true, true, true, true, true, true, true, true, false, false, false, false],
      [false, true, true, false, false, true, true, true, false, false, true, true, false, false, false],
      [true, true, true, false, false, true, true, true, false, false, true, true, true, false, false],
      [true, true, true, true, true, true, true, true, true, true, true, true, true, true, false],
      [true, true, false, true, true, true, true, true, true, true, false, true, true, true, false],
      [true, true, true, true, true, true, true, true, true, true, true, true, true, true, true],
      [true, true, true, true, false, false, true, true, false, false, true, true, true, true, false],
      [false, true, true, true, true, true, true, true, true, true, true, true, true, false, false],
      [false, false, true, true, true, true, true, true, true, true, true, true, false, false, false],
      [false, false, false, true, true, true, true, true, true, true, true, false, false, false, false],
      [false, false, false, false, true, true, true, true, true, true, false, false, false, false, false],
      [false, false, false, false, false, true, true, true, true, false, false, false, false, false, false],
      [false, false, false, false, false, false, true, true, false, false, false, false, false, false, false],
    ],
  },
  {
    id: 'turtle-15x15',
    name: '거북이',
    size: 15,
    description: '고급 - 거북이',
    solution: [
      [false, false, false, false, false, false, true, true, false, false, false, false, false, false, false],
      [false, false, false, false, false, true, true, true, true, false, false, false, false, false, false],
      [false, false, false, false, true, true, true, true, true, true, false, false, false, false, false],
      [false, false, false, true, true, true, true, true, true, true, true, false, false, false, false],
      [false, false, true, true, true, true, true, true, true, true, true, true, false, false, false],
      [false, true, true, true, true, true, true, true, true, true, true, true, true, false, false],
      [true, true, true, true, true, true, true, true, true, true, true, true, true, true, false],
      [true, true, true, true, true, true, true, true, true, true, true, true, true, true, true],
      [true, true, true, true, true, true, true, true, true, true, true, true, true, true, true],
      [false, true, true, true, true, true, true, true, true, true, true, true, true, true, false],
      [false, false, true, true, true, true, true, true, true, true, true, true, true, false, false],
      [false, false, false, true, true, true, true, true, true, true, true, true, false, false, false],
      [false, false, false, false, true, true, true, true, true, true, true, false, false, false, false],
      [false, false, false, false, false, true, true, true, true, true, false, false, false, false, false],
      [false, false, false, false, false, false, true, true, true, false, false, false, false, false, false],
    ],
  },
  {
    id: 'rabbit-15x15',
    name: '토끼',
    size: 15,
    description: '고급 - 토끼',
    solution: [
      [false, false, false, true, false, false, false, false, false, false, true, false, false, false, false],
      [false, false, true, true, true, false, false, false, false, true, true, true, false, false, false],
      [false, true, true, true, true, true, false, false, true, true, true, true, true, false, false],
      [true, true, true, true, true, true, true, true, true, true, true, true, true, true, false],
      [true, true, false, true, true, true, true, true, true, true, false, true, true, true, false],
      [true, true, true, true, true, true, true, true, true, true, true, true, true, true, true],
      [false, true, true, true, true, false, false, false, false, true, true, true, true, true, false],
      [false, false, true, true, true, true, true, true, true, true, true, true, true, false, false],
      [false, false, false, true, true, true, true, true, true, true, true, true, false, false, false],
      [false, false, false, false, true, true, true, true, true, true, true, false, false, false, false],
      [false, false, false, false, false, true, true, true, true, true, false, false, false, false, false],
      [false, false, false, false, false, false, true, true, true, false, false, false, false, false, false],
      [false, false, false, false, false, false, false, true, false, false, false, false, false, false, false],
      [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false],
      [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    ],
  },
  {
    id: 'dolphin-15x15',
    name: '돌고래',
    size: 15,
    description: '고급 - 돌고래',
    solution: [
      [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false],
      [false, false, false, false, false, false, false, true, false, false, false, false, false, false, false],
      [false, false, false, false, false, false, true, true, true, false, false, false, false, false, false],
      [false, false, false, false, false, true, true, true, true, true, false, false, false, false, false],
      [false, false, false, false, true, true, true, true, true, true, true, false, false, false, false],
      [false, false, false, true, true, true, true, true, true, true, true, true, false, false, false],
      [false, false, true, true, true, true, true, true, true, true, true, true, true, false, false],
      [false, true, true, true, true, true, true, true, true, true, true, true, true, true, false],
      [true, true, true, true, true, true, true, true, true, true, true, true, true, true, true],
      [false, true, true, true, true, true, true, true, true, true, true, true, true, true, false],
      [false, false, true, true, true, true, true, true, true, true, true, true, true, false, false],
      [false, false, false, true, true, true, true, true, true, true, true, true, false, false, false],
      [false, false, false, false, true, true, true, true, true, true, true, false, false, false, false],
      [false, false, false, false, false, true, true, true, true, true, false, false, false, false, false],
      [false, false, false, false, false, false, true, true, true, false, false, false, false, false, false],
    ],
  },
  {
    id: 'horse-15x15',
    name: '말',
    size: 15,
    description: '고급 - 말',
    solution: [
      [false, false, false, false, false, false, true, true, false, false, false, false, false, false, false],
      [false, false, false, false, false, true, true, true, true, false, false, false, false, false, false],
      [false, false, false, false, true, true, true, true, true, true, false, false, false, false, false],
      [false, false, false, true, true, true, true, true, true, true, true, false, false, false, false],
      [false, false, true, true, false, true, true, true, true, false, true, true, false, false, false],
      [false, true, true, true, true, true, true, true, true, true, true, true, true, false, false],
      [true, true, true, true, true, true, true, true, true, true, true, true, true, true, false],
      [true, true, false, true, true, true, true, true, true, true, false, true, true, true, false],
      [true, true, true, true, true, true, true, true, true, true, true, true, true, true, true],
      [false, true, true, true, true, true, true, true, true, true, true, true, true, false, false],
      [false, false, true, true, true, true, true, true, true, true, true, true, false, false, false],
      [false, false, false, true, true, true, true, true, true, true, true, false, false, false, false],
      [false, false, false, false, true, true, true, true, true, true, false, false, false, false, false],
      [false, false, false, false, false, true, true, true, true, false, false, false, false, false, false],
      [false, false, false, false, false, false, true, true, false, false, false, false, false, false, false],
    ],
  },
  {
    id: 'giraffe-15x15',
    name: '기린',
    size: 15,
    description: '고급 - 기린',
    solution: [
      [false, false, false, false, false, false, true, true, false, false, false, false, false, false, false],
      [false, false, false, false, false, true, true, true, true, false, false, false, false, false, false],
      [false, false, false, false, true, true, true, true, true, true, false, false, false, false, false],
      [false, false, false, true, true, false, true, true, false, true, true, false, false, false, false],
      [false, false, true, true, true, true, true, true, true, true, true, true, false, false, false],
      [false, true, true, true, true, true, true, true, true, true, true, true, true, false, false],
      [true, true, false, true, true, true, true, true, true, true, false, true, true, true, false],
      [true, true, true, true, true, true, true, true, true, true, true, true, true, true, true],
      [false, true, true, true, true, true, true, true, true, true, true, true, true, false, false],
      [false, false, true, true, true, true, true, true, true, true, true, true, false, false, false],
      [false, false, false, true, true, true, true, true, true, true, true, false, false, false, false],
      [false, false, false, false, true, true, true, true, true, true, false, false, false, false, false],
      [false, false, false, false, false, true, true, true, true, false, false, false, false, false, false],
      [false, false, false, false, false, false, true, true, true, false, false, false, false, false, false],
      [false, false, false, false, false, false, false, true, false, false, false, false, false, false, false],
    ],
  },
  {
    id: 'tiger-15x15',
    name: '호랑이',
    size: 15,
    description: '고급 - 호랑이',
    solution: [
      [false, false, false, false, true, true, true, true, true, false, false, false, false, false, false],
      [false, false, false, true, true, true, true, true, true, true, false, false, false, false, false],
      [false, false, true, true, true, true, true, true, true, true, true, false, false, false, false],
      [false, true, true, false, true, true, true, true, true, false, true, true, false, false, false],
      [true, true, true, true, true, true, true, true, true, true, true, true, true, false, false],
      [true, true, true, true, true, true, true, true, true, true, true, true, true, true, false],
      [true, true, false, true, true, true, true, true, true, true, false, true, true, true, false],
      [true, true, true, true, true, true, true, true, true, true, true, true, true, true, true],
      [true, true, false, true, true, true, true, true, true, true, false, true, true, true, false],
      [false, true, true, true, true, true, true, true, true, true, true, true, true, false, false],
      [false, false, true, true, true, true, true, true, true, true, true, true, false, false, false],
      [false, false, false, true, true, true, true, true, true, true, true, false, false, false, false],
      [false, false, false, false, true, true, true, true, true, true, false, false, false, false, false],
      [false, false, false, false, false, true, true, true, true, false, false, false, false, false, false],
      [false, false, false, false, false, false, true, true, false, false, false, false, false, false, false],
    ],
  },
  {
    id: 'dragon-15x15',
    name: '용',
    size: 15,
    description: '고급 - 용',
    solution: [
      [false, false, false, false, false, false, true, true, false, false, false, false, false, false, false],
      [false, false, false, false, false, true, true, true, true, false, false, false, false, false, false],
      [false, false, false, false, true, true, true, true, true, true, false, false, false, false, false],
      [false, false, false, true, true, false, true, true, false, true, true, false, false, false, false],
      [false, false, true, true, true, true, true, true, true, true, true, true, false, false, false],
      [false, true, true, true, true, true, true, true, true, true, true, true, true, false, false],
      [true, true, true, true, true, true, true, true, true, true, true, true, true, true, false],
      [true, true, false, true, true, true, true, true, true, true, false, true, true, true, false],
      [true, true, true, true, true, true, true, true, true, true, true, true, true, true, true],
      [false, true, true, true, true, true, true, true, true, true, true, true, true, false, false],
      [false, false, true, true, true, true, true, true, true, true, true, true, false, false, false],
      [false, false, false, true, true, true, true, true, true, true, true, false, false, false, false],
      [false, false, false, false, true, true, true, true, true, true, false, false, false, false, false],
      [false, false, false, false, false, true, true, true, true, false, false, false, false, false, false],
      [false, false, false, false, false, false, true, true, false, false, false, false, false, false, false],
    ],
  },
  {
    id: 'unicorn-15x15',
    name: '유니콘',
    size: 15,
    description: '고급 - 유니콘',
    solution: [
      [false, false, false, false, false, false, false, true, false, false, false, false, false, false, false],
      [false, false, false, false, false, false, true, true, true, false, false, false, false, false, false],
      [false, false, false, false, false, true, true, true, true, true, false, false, false, false, false],
      [false, false, false, false, true, true, true, true, true, true, true, false, false, false, false],
      [false, false, false, true, true, false, true, true, true, false, true, true, false, false, false],
      [false, false, true, true, true, true, true, true, true, true, true, true, true, false, false],
      [false, true, true, true, true, true, true, true, true, true, true, true, true, true, false],
      [true, true, true, false, true, true, true, true, true, true, false, true, true, true, false],
      [true, true, true, true, true, true, true, true, true, true, true, true, true, true, true],
      [false, true, true, true, true, true, true, true, true, true, true, true, true, false, false],
      [false, false, true, true, true, true, true, true, true, true, true, true, false, false, false],
      [false, false, false, true, true, true, true, true, true, true, true, false, false, false, false],
      [false, false, false, false, true, true, true, true, true, true, false, false, false, false, false],
      [false, false, false, false, false, true, true, true, true, false, false, false, false, false, false],
      [false, false, false, false, false, false, true, true, false, false, false, false, false, false, false],
    ],
  },
]
